### ISSUE TITLE
I have the newest version, but-

### ISSUE THREAD

**Issue by ThickThighsBestThighs** [Team-Fruit/SignPicture#11]
SignPicture always asks me to update, even though I have the newest version.
I've removed the old version and the old config file from both the server and my client.
I've triple checked to make sure that both the server and my client are using the newest version.
I've restarted both the server and my client three times now.
I'm using SignPicture-1.7.10-2.6.1.

![glitch](https://cloud.githubusercontent.com/assets/12576021/21294512/e522f754-c503-11e6-9121-f1670ed04545.png)

**Comment by sjcl** [comment]
I'm sorry. I will fix it immediately.

**Comment by Kamesuta** [comment]
Wow! You are cutting edge! I immediately noticed it, fixed it, and replaced it with an existing version. Please update in game or download modified version from site. Thank you for the quick report.

---
わぉ！あなたは最先端ですね！私もすぐに気づいて修正し、既存のバージョンと置き換えました。ゲーム内更新またはサイトから修正版をダウンロードしてください。素早い報告ありがとうございます。
