### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by EvilCh33z** [Team-Fruit/SignPicture#12]
Help?
Client crashing on connect.
Any suggestions or help would be appreciated! 

[crash-report-client.txt](https://github.com/Team-Fruit/SignPicture/files/659678/crash-2016-12-18_14.28.36-client.txt)

**Comment by Kamesuta** [comment]
Thank you for reporting the bug. If it is NoClassDefFoundError, it seems to be different from this development environment. For now, please try the latest version 2.6.1. If it crashes, paste the crash report again.

---
バグ報告ありがとうございます。NoClassDefFoundErrorですと、こちらの開発環境と異なる環境の様です。とりあえず、最新版2.6.1をお試しください。クラッシュしましたら、改めてクラッシュレポートを貼り付けてください。

**Comment by EvilCh33z** [comment]
yeah, just realized the versions werent current. testing now will reply with results very soon

**Comment by EvilCh33z** [comment]
My bad, man. Working fine now that Ive updated to current 1.10.2 version.
sorry for posting an issue before properly reading through.

Keep up the good work! I've been ecstatic about this mod since I found it and I love putting random custom pictures in my server patrons' houses and such!
