### ISSUE TITLE
Consecutively placing signpictures makes the offset go crazy

### ISSUE THREAD

**Issue by JosEffigy** [Team-Fruit/SignPicture#16]
The first sign picture works fine. placing more signpictures and changing the offset everytime will make it bug out. 
possible mods that will change Minecraft's Math functions:
Fastcraft 1.25
Optifine DU7
BetterFPS

**Comment by JosEffigy** [comment]
this eventually leads to the photo not visible when previewing and placing it.
also the offset bug will not dissapear unless restart the game. doesnt fix if only leave the world

**Comment by Kamesuta** [comment]
I'm sorry. We will fix it with the next update.

**Comment by JosEffigy** [comment]
additional information:
this was on version 1.7.10

**Comment by PigCart** [comment]
I think this is back in 1.12.
The offset increases every time I close the menu and it won't reset.
If I set it to 2 it goes up in powers of 2.
Happens without any other mods.

**Comment by JosEffigy** [comment]
Perhaps this is on Signpicture 2.7.1 for all versions of minecraft. I confirmed this to occur in this specific build.

**Comment by sjcl** [comment]
It was fixed in 2.8.0. I would absolutely like you to try that out.
