### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by or1ks** [Team-Fruit/SignPicture#17]
Hello. Help me pls.
![2017-04-17_11 41 08](https://cloud.githubusercontent.com/assets/27673592/25084123/8e3a6be8-2363-11e7-93ba-d4699facc294.png)
![2017-04-17_11 40 47](https://cloud.githubusercontent.com/assets/27673592/25084128/93afff84-2363-11e7-9d8e-9a21ad38f2bf.png)
![2017-04-17_11 40 05](https://cloud.githubusercontent.com/assets/27673592/25084129/95fdf4ee-2363-11e7-9a25-06568649218c.png)
![2017-04-17_11 41 08](https://cloud.githubusercontent.com/assets/27673592/25084130/97e2200a-2363-11e7-965b-96ef04e87ce5.png)

**Comment by Kamesuta** [comment]
Thank you for the report. As I already know bugs, I'd like to fix it soon.

**Comment by sjcl** [comment]
It was fixed in 2.8.0. I would absolutely like you to try that out.
