### ISSUE TITLE
local files

### ISSUE THREAD

**Issue by PigCart** [Team-Fruit/SignPicture#19]
Hey I've been using signpicture for a while and it is **amazing.**
Unfortunately some servers don't let URLs be put onto signs which kinda sucks...
Would it be possible to have a folder within the signpic folder in .minecraft for images that the mod can use? This could also be useful for offline mode if you want to use an image and can't upload it.

**Comment by sjcl** [comment]
Local files can be load from the resource pack. 
For example, `/assets/hoge/fuga.png` is `!hoge:fuga.png`.
You can add images to uncompressed resource packs and use them.

**Comment by PigCart** [comment]
I tried this for a while and it does not appear to work for me.
I created a new resource pack to put images in and tried things like:
!assets:minecraft:test.png
!pack:assets:minecraft:test.png
!resourcepacks:pack:assets:minecraft:test.png
Is there something I am missing?

**Comment by sjcl** [comment]
[![https://gyazo.com/43f737a44b244e999b3c36c3aa7ee9e2](https://gyazo.com/43f737a44b244e999b3c36c3aa7ee9e2/raw)](https://gyazo.com/43f737a44b244e999b3c36c3aa7ee9e2)
![image](https://user-images.githubusercontent.com/16951483/27160523-e178c438-51af-11e7-8198-9046c883049f.png)
[![https://gyazo.com/ca81056874b690630e1cd655f3baf3a6](https://gyazo.com/ca81056874b690630e1cd655f3baf3a6/raw)](https://gyazo.com/ca81056874b690630e1cd655f3baf3a6)

You can write like this.
