### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by iPencil** [Team-Fruit/SignPicture#2]
Heya, I'm using 1.10.2-2.1.5 in my modpack currently and I'm getting random crashes:

http://pastebin.com/9kieeYiP

and

http://pastebin.com/fqPqpAsQ

I saw that the 1.10.2 version is behind the other versions, are you actively maintaining it? Would be awesome if you could update/fix it! Great mod btw, we use it for our servers spawn :)

**Comment by Kamesuta** [comment]
1.9.4,1.10.2 version of the correspondence sorry late. In a state in which the contact, such as in flat glass in F3 mode, a bug that crashes when looking at an empty place. In SignPicture2.3.0 of 1.7.10,1.8.9 it is already measures already. So I'll hurry the version correspondence, please wait for a while.

---
1.9.4、1.10.2のバージョンの対応が遅くて申し訳ありません。F3モードで板ガラスなどに接した状態で、なにもない場所を見るとクラッシュするバグです。1.7.10、1.8.9のSignPicture2.3.0ではすでに対策済みです。私はバージョン対応を急ぎますので、もうしばらくお待ちください。

**Comment by iPencil** [comment]
Okay, no worries all good :)

Thanks for the quick reply and for making this amazing mod! :)

**Comment by Kamesuta** [comment]
It has released a version 2.3.0 that corresponds to the Minecraft 1.9.4,1.10.2. This will also have been corrected bug that crash. Thank you the SignPicture in the future.

---
Minecraft 1.9.4、1.10.2に対応したバージョン2.3.0をリリースしました。これはクラッシュするバグも修正してあります。今後もSignPictureをよろしくお願いします。

**Comment by iPencil** [comment]
Thank you very much! We just updated our modpack and it works flawlessly! Thanks for doing this so quickly :)
