### ISSUE TITLE
[1.10.2] Render and inventory issues

### ISSUE THREAD

**Issue by ruyanve** [Team-Fruit/SignPicture#3]
Using Forge 2095
SignPicture-1.10.2-2.3.0-universal
Without optifine

I am getting some weird issues after placing a couple pictures.
My inventory is full but it shows up empty, if I shift my field of view the inventory shows up fine again. So it's only when looking in a certain direction.

![inventory](http://i.imgur.com/zB4YFUj.png)

Related but different is, that when looking from a specific angle the already placed pictures move with my mouse movement, as well as all other particles on screen. Hard to describe, it's almost like the preview mode, but after a certain angle the pictures snap back to the place they belong.

![particles](http://i.imgur.com/8CfpRwz.png)

**Comment by Kamesuta** [comment]
Thanks for reporting!
I think that your console has prompted a warning of a lot of GL error, but the bug in this update will be fixed!
Also fixes inventory of drawing bug.
New version is [Available](https://github.com/Team-Fruit/SignPicture/releases/tag/1.10.2-2.3.1)!

**Comment by ruyanve** [comment]
Fixed, thank you!
