### ISSUE TITLE
goo.gl shutting down

### ISSUE THREAD

**Issue by lolita-is-godddd** [Team-Fruit/SignPicture#41]
**If this message different from Japanese, right message is japanese.**
**このえいごのめっせーじがにほんごとちがうばあい、ただしいめっせーじはにほんごのほうです**

by 2019 Mar 30, goo.gl will be COMPLETY shutdowned even if via api.
2019/3/30にgoo.glは完全にAPIを経由しても新規リンクが発行できなくなります。

so i think add implementazition another shortener.
そのため、ほかの短縮URLの対応を検討すべきだと考えます。

**Comment by ErdbeerbaerLP** [comment]
Starting March 30, 2018, we will be turning down support for goo.gl URL shortener. From April 13, 2018 only existing users will be able to create short links on the goo.gl console. You will be able to view your analytics data and download your short link information in csv format for up to one year, until March 30, 2019, when we will discontinue goo.gl. Previously created links will continue to redirect to their intended destination. Please see this [blog post](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html) for more details.

(Better english)

**Comment by sjcl** [comment]
SignPicture supports both goo.gl and bit.ly.
When goo.gl is deprecated, you can use bit.ly.
