### ISSUE TITLE
[Suggestion] Make sign MCMP compatible.

### ISSUE THREAD

**Issue by Dushess** [Team-Fruit/SignPicture#5]
Will be nice to add possibility to place something around it. By example - C&B bits or MCMP covers.
In addition maybe make picture (sign) placement not only on a block but on mcmp-surface too, but i think it's unable to do.

**Comment by Kamesuta** [comment]
Sorry, I can not understand C & B bits and MCMP covers.
Please tell me a bit more about that Mod.
Also, mostly, you can realize by placing the signboard behind the scenes and shifting it using offset and rotation. So I really need to implement it in SignPicture?

**Comment by Dushess** [comment]
Minecraft multipart, that can provide division of single block to parts.
Chisels&Bits is MCMP compatible mod, creating 16x16x16 structure inside block.
Cover - it's part of old ForgeMultipart, same implementation, but mostly panels, not only bits.

**Comment by Dushess** [comment]
I'm trying to realize a display board, but not block sized. I mean something like 8 bits tall and 48 wide, that requires useful space above and under the signboard.

**Comment by Kamesuta** [comment]
SignPicture is a complete client mod. It means not to add a new block. In addition, this mod is made in consideration of operating in the vanilla environment. So the only thing this mod can do is save the text on the signboard. Can you make your wish come true under this condition? If so, we will be waiting for a concrete method.

---
SignPictureは完全なクライアントmodです。それは、新たなブロックを追加しないことを意味しています。また、このmodはバニラ環境で動作することを考慮して作られています。よって、唯一このmodができることは看板にテキストを保存することのみです。あなたはこの条件のもとであなたの望みを叶えることができますか？もしできそうであれば、具体的な方法をお待ちしております。

**Comment by Dushess** [comment]
In this case we have one method, change stock signboard and make it MCMP compatible, like th
![2016-11-21_20 18 20](https://cloud.githubusercontent.com/assets/15954961/20493316/af69806a-b031-11e6-9ba2-15b8c86bae2c.png)
at.

**Comment by Kamesuta** [comment]
If you want to fine-tune the settings such as size, offset, rotation, etc., try clicking the adjustment button while holding down the Shift key or Ctrl key. You probably will be able to adjust the Shift key by 1/10 and the Ctrl key by 1/100.

---
もし、サイズやオフセット、回転などの設定を微調整したいのであれば、調節ボタンを、ShiftキーやCtrlキーを押しながらクリックしてみてください。きっとShiftキーは10分の1、Ctrlキーは100分の1づつ調節できることでしょう。

**Comment by Dushess** [comment]
> If you want to fine-tune the settings such as size, offset, rotation, etc.

But it's other thing, sign will stay here, and will interferes me anyway

**Comment by sjcl** [comment]
Is that a problem with the thickness of the sign?

**Comment by Dushess** [comment]
> Is that a problem with the thickness of the sign?

A bit, as i say, sigh consuming all block space and not MCMP compatible (I recalled). This seems, bits cannot be placed around sign? but inside the same block.

**Comment by Kamesuta** [comment]
I've never seen signs overlapping with ForgeMultiPart or MinecraftMultiPart, but can we really put on signs in a block? Also, what does it look like if you overlay SignPicture in practice?

---
私はForgeMultiPartやMinecraftMultiPartで看板を重ねているのを見たことがありませんが、実際には看板を重ねることができるのでしょうか。また、実際にSignPictureを重ねるとどのように見えるのでしょうか。

**Comment by Dushess** [comment]
Can, sign IS a block, only visual is thin wooden tablet.

**Comment by Kamesuta** [comment]
It seems like it can not do without adding a new block. Since SignPicture is mod modifying "appearance" to the last, you can not add or change blocks.

---
それは新たにブロックを追加しないとできないことのように思われます。SignPictureはあくまでも「見た目」を変更するmodなので、ブロックの追加、変更などはできません。

**Comment by Dushess** [comment]
Hmm, then i should ask Amadornes, for replacing stock signboard to MCMP compatible.

**Comment by sjcl** [comment]
If this Mod is not included, is Sign compatible with MCSP?

**Comment by Dushess** [comment]
No

**Comment by sjcl** [comment]
As you say, This Mod does not change the block of Sign.
Therefore, if compatibility to Sign is provided by MCMP, this Mod never interferes with it.

**Comment by Dushess** [comment]
But he uses standard sign, right.

**Comment by sjcl** [comment]
Because Sign Block and rendering are separate, this Mod uses only the standard Sign to change only the appearance.

**Comment by Dushess** [comment]
Right, forget about this, maybe soometime.....

**Comment by sjcl** [comment]
Sorry, this mod can not achieve compatibility with MCMP ... 
I hope compatibility will be added by MCMP :-)
