### ISSUE TITLE
Does nothing? Keeps changing sign to ERROR Invalid URL

### ISSUE THREAD

**Issue by SkittyChips** [Team-Fruit/SignPicture#52]
This mod is really cool if you want to have signs that only say ERROR Invalid URL. I pasted in https://bit.ly/2rl5Svf but the moment I place it down the sign text turned to #{} and it showed an error image. _**The thing is the preview always shows the correct image, but doesn't when I place it down**_

**Comment by SkittyChips** [comment]
https://imgur.com/gallery/XVpGijS 
The url obviously doesn't work since I totally didn't just put the url into my browser and it led to a valid png file.

**Comment by SkittyChips** [comment]
Oh I forgot, I want to applaud the developers for adding tons of documentation (none) and many useful (useless) buttons. I rate this mod a 10, out of 10000. Honestly don't download it. They probably farm your data. I mean even many of the assets and designs used in the mod are stolen from Osu! the game.

**Comment by SkittyChips** [comment]
MaxRetryCountOver, won't even let me do anything now. I'm going to keep listing all of the bugs, I'm guessing that I can get to 100 in 24 hours.

**Comment by SkittyChips** [comment]
I can't even place normal signs. Placing a sign automatically places the error picture.

**Comment by yahho** [comment]
Follow the issues section on this repository's readme. 
We need more required infomation for detecting your problems.

**Comment by yahho** [comment]
Duplicate of #27
