### ISSUE TITLE
Can not upload and show images in 1.12.2

### ISSUE THREAD

**Issue by DreamUniverse843** [Team-Fruit/SignPicture#55]
Nice to meet you,guys!

I like your mod very much and I made a huge project by this great mod. I've been used it for a long time,and recently I found a bug about this mod.

Yesterday I noticed uploading images stopped working. As a result, when I try uploading images by your mod, it shows nothing and that's it. I thought my network didn't work,however,it worked well. And these day the condition seems to be worse.I even can't show the images I've already uploaded before,while this problem have never appeared before. Even if I restart the game,it still doesn't work,and it said that some images can not load.

Now,I work with this mod and it's really important for me to make great projects.Is there any way to solve this problem?

Thanks!

SignPicture-1.12.2-2.8.1-universal

**Comment by KisaragiEffective** [comment]
any other mods?

**Comment by DreamUniverse843** [comment]
I have one mod called RailCraft,ant it's not RealTrainMod. I really need your mod to make images of subway stations.Please fix up this problem soon.Thank you!

**Comment by DreamUniverse843** [comment]
I've already known that RealTrainMod is not supported,so I didn't use it,but RailCraft.
