### ISSUE TITLE
Crash w/ iChunUtil?

### ISSUE THREAD

**Issue by WenXin20** [Team-Fruit/SignPicture#6]
Forge 2151
Sign Pic v2.4.6
[iChunUtil](https://minecraft.curseforge.com/projects/ichunutil) v6.1.0
It crashes on game launch and the report says something about iChunUtil and rendering.
[Crash Log](http://pastebin.com/BF9LQ4Pd)

**Comment by Kamesuta** [comment]
Thank you for reporting.
I changed the cause location from the crash report. In this environment it does not crash. I will post the alpha version here so please report again whether the bug has been improved.
[SignPicture-1.10.2-2.4.7.alpha-universal.zip](https://github.com/Team-Fruit/SignPicture/files/614066/SignPicture-1.10.2-2.4.7.alpha-universal.zip)

---
ご報告ありがとうございます。
クラッシュリポートから原因の場所を変更しました。こちらの環境ではクラッシュしなくなりました。α版をここに載せますのでバグが改善されたかどうかをまたご報告ください。

**Comment by WenXin20** [comment]
It works :)
