### ISSUE TITLE
Forge 2151 1.10.2-2.4.6 Exception on start up

### ISSUE THREAD

**Issue by Hastling** [Team-Fruit/SignPicture#8]
http://pastebin.com/1e62P1PV

**Comment by sjcl** [comment]
#6 The cause is the same. Please wait for correspondence.

**Comment by Hastling** [comment]
Not exactly a duplicate as I do not have iChunUtil installed.

**Comment by sjcl** [comment]
BetterThanBunnies seems to be doing the same implementation as IChunUtil. 
Now we have released a modified version. You can download from here. 
https://minecraft.curseforge.com/projects/sign-picture/files/2349404

**Comment by Hastling** [comment]
It seems to be working. Thanks for the quick fix.
